# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DivorceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('laws', models.CharField(blank=True, max_length=500, null=True)),
                ('place', models.CharField(blank=True, max_length=30, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('lb1', models.IntegerField(blank=True, null=True)),
                ('lb2', models.IntegerField(blank=True, null=True)),
                ('lb3', models.IntegerField(blank=True, null=True)),
                ('lb4', models.IntegerField(blank=True, null=True)),
                ('lb5', models.IntegerField(blank=True, null=True)),
                ('lb6', models.IntegerField(blank=True, null=True)),
                ('lb7', models.IntegerField(blank=True, null=True)),
                ('lb8', models.IntegerField(blank=True, null=True)),
                ('lb9', models.IntegerField(blank=True, null=True)),
                ('lb10', models.IntegerField(blank=True, null=True)),
                ('lb11', models.IntegerField(blank=True, null=True)),
                ('lb12', models.IntegerField(blank=True, null=True)),
                ('lb13', models.IntegerField(blank=True, null=True)),
                ('lb14', models.IntegerField(blank=True, null=True)),
                ('lb15', models.IntegerField(blank=True, null=True)),
                ('lb16', models.IntegerField(blank=True, null=True)),
                ('lb17', models.IntegerField(blank=True, null=True)),
                ('lb18', models.IntegerField(blank=True, null=True)),
                ('lb19', models.IntegerField(blank=True, null=True)),
                ('lb20', models.IntegerField(blank=True, null=True)),
                ('lb21', models.IntegerField(blank=True, null=True)),
                ('mental_pros', models.IntegerField(blank=True, null=True)),
                ('mental_def', models.IntegerField(blank=True, null=True)),
                ('soldier_pros', models.IntegerField(blank=True, null=True)),
                ('soldier_def', models.IntegerField(blank=True, null=True)),
                ('missing_pros', models.IntegerField(blank=True, null=True)),
                ('missing_def', models.IntegerField(blank=True, null=True)),
                ('foreign_pros', models.IntegerField(blank=True, null=True)),
                ('foreign_def', models.IntegerField(blank=True, null=True)),
                ('casedate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'divorce_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
    ]
